import { Passport, IoTEvent, AuditEntry } from './types';

export const PASSPORTS: Passport[] = [
  {
    id: 'DPP-4A2F',
    name: 'EcoWash Pro 7kg',
    manufacturer: 'Bosch GmbH',
    category: 'appliance',
    manufacturedAt: '2024-11-12',
    dataSource: 'iot',
    materials: [
      { name: 'Steel', pct: 58, recycled: 72 },
      { name: 'Polypropylene', pct: 22, recycled: 18 },
      { name: 'Copper', pct: 12, recycled: 45 },
      { name: 'Glass', pct: 8, recycled: 30 },
    ],
    repairScore: 8.2,
    spareYears: 12,
    co2: 87.4,
    status: 'verified',
    proof: 'aleo1qgr34p...9kz2',
    carbon: { mfg: 42, transport: 18, use: 21, eol: 6.4 },
  },
  {
    id: 'DPP-7C81',
    name: 'SolarPanel X200',
    manufacturer: 'SunTech EU',
    category: 'energy',
    manufacturedAt: '2024-09-03',
    dataSource: 'csv',
    materials: [
      { name: 'Silicon', pct: 45, recycled: 8 },
      { name: 'Aluminium', pct: 30, recycled: 88 },
      { name: 'EVA Film', pct: 15, recycled: 0 },
      { name: 'Glass', pct: 10, recycled: 22 },
    ],
    repairScore: 5.1,
    spareYears: 8,
    co2: 124.8,
    status: 'verified',
    proof: 'aleo1mn8xl...4qj9',
    carbon: { mfg: 95, transport: 12, use: 8, eol: 9.8 },
  },
  {
    id: 'DPP-2B5E',
    name: 'BioBottle 500ml',
    manufacturer: 'GreenPack SRL',
    category: 'packaging',
    manufacturedAt: '2025-01-08',
    dataSource: 'manual',
    materials: [
      { name: 'rPET', pct: 80, recycled: 95 },
      { name: 'Bio-HDPE', pct: 15, recycled: 40 },
      { name: 'Adhesive', pct: 5, recycled: 0 },
    ],
    repairScore: 2.4,
    spareYears: 0,
    co2: 3.2,
    status: 'pending',
    proof: null,
    carbon: { mfg: 2.1, transport: 0.7, use: 0.2, eol: 0.2 },
  },
  {
    id: 'DPP-9D3A',
    name: 'ThermoFrame 45W',
    manufacturer: 'Heatex AB',
    category: 'electronics',
    manufacturedAt: '2024-07-19',
    dataSource: 'iot',
    materials: [
      { name: 'Aluminium', pct: 62, recycled: 91 },
      { name: 'PCB FR-4', pct: 20, recycled: 12 },
      { name: 'Silicone', pct: 10, recycled: 0 },
      { name: 'Copper', pct: 8, recycled: 55 },
    ],
    repairScore: 7.8,
    spareYears: 10,
    co2: 56.1,
    status: 'verified',
    proof: 'aleo1pk2we...8rs1',
    carbon: { mfg: 32, transport: 9, use: 12, eol: 3.1 },
  },
  {
    id: 'DPP-6F4C',
    name: 'NanoFilter Membrane',
    manufacturer: 'AquaTech NV',
    category: 'industrial',
    manufacturedAt: '2025-02-14',
    dataSource: 'api',
    materials: [
      { name: 'PVDF', pct: 70, recycled: 5 },
      { name: 'Steel mesh', pct: 20, recycled: 66 },
      { name: 'Epoxy', pct: 10, recycled: 0 },
    ],
    repairScore: 4.3,
    spareYears: 5,
    co2: 41.9,
    status: 'fail',
    proof: null,
    carbon: { mfg: 28, transport: 7, use: 5, eol: 1.9 },
  },
];

export const IOT_FEED: IoTEvent[] = [
  { id: 'DPP-4A2F', device: 'RPi-003', event: 'Temp sensor POST — carbon update', time: '2 min ago', status: 'live' },
  { id: 'DPP-9D3A', device: 'RPi-007', event: 'Zod validation pass — proof queued', time: '8 min ago', status: 'live' },
  { id: 'DPP-6F4C', device: 'RPi-011', event: 'Schema mismatch — missing repairScore', time: '14 min ago', status: 'warn' },
  { id: 'DPP-4A2F', device: 'RPi-003', event: 'ZK proof generated — aleo1pk2...', time: '22 min ago', status: 'live' },
  { id: 'DPP-2B5E', device: 'Manual', event: 'Entry submitted — awaiting proof', time: '1 hr ago', status: 'live' },
];

export const AUDIT: AuditEntry[] = [
  { ts: '2025-06-07 14:32', action: 'upsert', id: 'DPP-4A2F', src: 'iot', schema: '1.0.0', hash: 'sha256:4a2f...' },
  { ts: '2025-06-07 13:58', action: 'proof_gen', id: 'DPP-9D3A', src: 'iot', schema: '1.0.0', hash: 'sha256:9d3a...' },
  { ts: '2025-06-07 12:11', action: 'validation_fail', id: 'DPP-6F4C', src: 'iot', schema: '1.0.0', hash: '—' },
  { ts: '2025-06-07 11:40', action: 'upsert', id: 'DPP-7C81', src: 'csv', schema: '1.0.0', hash: 'sha256:7c81...' },
  { ts: '2025-06-07 09:22', action: 'upsert', id: 'DPP-2B5E', src: 'manual', schema: '1.0.0', hash: 'sha256:2b5e...' },
];
